# /// script
# requires-python = ">=3.11"
# dependencies = ["numpy>=1.26", "scikit-learn>=1.5"]
# ///
"""Train M1K3's per-turn tool router and write its Swift weights.

    uv run tools/router/train_tool_router.py        # from macos/

Two heads over the same Apple NLEmbedding sentence vector.

The gate (ToolNeedRouterWeights): a logistic layer, does this chat turn
need a tool? The threshold is picked by 5-fold cross-validation to keep 97% of
the training set's tool asks, because a miss hides a tool the turn needed. The
eval fixtures are the test set and never enter training (scratch/laya-spike,
FINDINGS round 3: 42/42 real tool asks kept, 28/74 no-tool turns freed).

Output: Sources/M1K3Chat/ToolNeedRouterWeights.swift (generated; do not edit).

The group head (ToolGroupRouterWeights): a softmax over the data's groups,
which tool family a tools-verdict turn wants, so the app can run a read-only
tool with no model in the loop (ToolGroupRouter). It only has to be right when
it speaks: the dispatch floor is the lowest top-probability at which the
cross-validated picks that would dispatch (top group is not `none`) are still
PRECISION right. Below the floor it abstains and the turn takes the picker or
the agent as before. A wrong tool is a wrong answer; an abstention is only slower.

Signed: Kev + claude-opus-5-5, 2026-09-26, Confidence 0.8 (the recipe is the
spike's, reproduced; the data is synthetic until a shadow log exists). Prior: Unknown.
Review: Kev + claude-opus-5-5, 2026-10-07 — the group head, so every tier can dispatch
read-only tools without thinking or a tool-call format. Confidence 0.7 (the floor's
precision is cross-validated on synthetic data; the live gain is the eval arm's to show).
"""
from __future__ import annotations

import json
import subprocess
import tempfile
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
MACOS = HERE.parents[1]
DATA = HERE / "data" / "tool_router_train.json"
OUT = MACOS / "Sources" / "M1K3Chat" / "ToolNeedRouterWeights.swift"
GROUP_OUT = MACOS / "Sources" / "M1K3Chat" / "ToolGroupRouterWeights.swift"
RECALL = 0.97
C = 4.0
# The group head's order is the Swift arrays' order; ToolGroupRouter maps each name.
GROUPS = ["none", "device", "knowledge", "web", "activity", "script"]
PRECISION = 0.95


def labels(items: list[dict]) -> np.ndarray:
    return np.array([item["group"] != "none" for item in items])


def group_labels(items: list[dict]) -> np.ndarray:
    """Each item's index in GROUPS; an unknown group is a data error, not a new class."""
    unknown = {item["group"] for item in items} - set(GROUPS)
    if unknown:
        raise ValueError(f"groups not in GROUPS: {sorted(unknown)}")
    return np.array([GROUPS.index(item["group"]) for item in items])


def dispatch_floor(probabilities: np.ndarray, truth: np.ndarray, precision: float = PRECISION) -> float:
    """The lowest top-probability floor at which the picks that would dispatch are
    still `precision` right. A pick dispatches when its top group is not `none`
    (index 0) and its top probability is at or above the floor. 1.0 when no floor
    reaches the precision: the head then never speaks (above 1.0 nothing passes)."""
    top = probabilities.argmax(axis=1)
    confidence = probabilities.max(axis=1)
    speaks = top != 0
    for floor in np.sort(np.unique(confidence[speaks])):
        chosen = speaks & (confidence >= floor)
        if (top[chosen] == truth[chosen]).mean() >= precision:
            return float(floor)
    return 1.0 + 1e-9


def normalise(vectors: np.ndarray) -> np.ndarray:
    return vectors / np.linalg.norm(vectors, axis=1, keepdims=True)


def recall_threshold(probabilities: np.ndarray, is_tool: np.ndarray, recall: float = RECALL) -> float:
    """The highest threshold that still keeps `recall` of the tool asks."""
    return float(np.quantile(probabilities[is_tool], 1.0 - recall))


def render_swift(weights: np.ndarray, bias: float, threshold: float, count: int, cv_note: str) -> str:
    rows = [", ".join(f"{w:.9g}" for w in weights[i : i + 8]) for i in range(0, len(weights), 8)]
    body = ",\n        ".join(rows)
    return f"""//
//  ToolNeedRouterWeights.swift
//  M1K3Chat
//
//  GENERATED by tools/router/train_tool_router.py; do not edit by hand.
//  A logistic layer over NLEmbedding's English sentence vector (L2-normalised):
//  P(this turn needs a tool). Trained on {count} synthetic labelled prompts
//  (tools/router/data); the eval fixtures are its test set.
//  {cv_note}
//

enum ToolNeedRouterWeights {{
    /// At or above: keep the tools. Picked to keep {RECALL:.0%} of tool asks in cross-validation.
    static let threshold: Double = {threshold:.9g}
    static let bias: Double = {bias:.9g}
    static let weights: [Double] = [
        {body},
    ]
}}
"""


def render_group_swift(
    groups: list[str], weights: np.ndarray, biases: np.ndarray, floor: float, count: int, cv_note: str
) -> str:
    rows = []
    for row in weights:
        chunks = [", ".join(f"{w:.9g}" for w in row[i : i + 8]) for i in range(0, len(row), 8)]
        rows.append("[\n            " + ",\n            ".join(chunks) + ",\n        ]")
    body = "".join(f"\n        {row}," for row in rows)
    trained = f"Trained on {count} synthetic labelled prompts (tools/router/data)" if count else (
        "UNTRAINED: no groups, so the head abstains on every turn. Run the trainer on a Mac"
    )
    return f"""//
//  ToolGroupRouterWeights.swift
//  M1K3Chat
//
//  GENERATED by tools/router/train_tool_router.py; do not edit by hand.
//  A softmax layer over NLEmbedding's English sentence vector (L2-normalised):
//  which tool family a tools-verdict turn wants (ToolGroupRouter).
//  {trained}; the eval fixtures are its test set.
//  {cv_note}
//

enum ToolGroupRouterWeights {{
    /// Row order of `weights` and `biases`.
    static let groups: [String] = [{", ".join(f'"{g}"' for g in groups)}]
    /// At or above (top probability): dispatch. Picked for {PRECISION:.0%} precision in cross-validation.
    static let floor: Double = {floor:.9g}
    static let biases: [Double] = [{", ".join(f"{b:.9g}" for b in biases)}]
    static let weights: [[Double]] = [{body}
    ]
}}
"""


def embed(prompts: list[str]) -> np.ndarray:
    with tempfile.TemporaryDirectory() as tmp:
        source, target = Path(tmp) / "in.json", Path(tmp) / "out.json"
        source.write_text(json.dumps(prompts))
        subprocess.run(["swift", str(HERE / "embed.swift"), str(source), str(target)], check=True)
        return np.array(json.loads(target.read_text()), dtype=np.float64)


def main() -> None:
    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import StratifiedKFold, cross_val_predict

    items = json.loads(DATA.read_text())["items"]
    x, y = normalise(embed([item["prompt"] for item in items])), labels(items)
    model = LogisticRegression(C=C, max_iter=5000, class_weight="balanced")
    folds = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
    cv = cross_val_predict(model, x, y, cv=folds, method="predict_proba")[:, 1]
    threshold = recall_threshold(cv, y)
    freed = int((cv[~y] < threshold).sum())
    note = f"CV at the threshold: {int((cv[y] >= threshold).sum())}/{int(y.sum())} tool asks kept, {freed}/{int((~y).sum())} chat turns freed."
    model.fit(x, y)
    OUT.write_text(render_swift(model.coef_[0], float(model.intercept_[0]), threshold, len(items), note))
    print(f"wrote {OUT.relative_to(MACOS)}: threshold {threshold:.3f}; {note}")

    # The group head: same vectors, one class per group (multinomial with lbfgs).
    truth = group_labels(items)
    head = LogisticRegression(C=C, max_iter=5000, class_weight="balanced")
    cv_groups = cross_val_predict(head, x, truth, cv=folds, method="predict_proba")
    floor = dispatch_floor(cv_groups, truth)
    top, confidence = cv_groups.argmax(axis=1), cv_groups.max(axis=1)
    speaks = (top != 0) & (confidence >= floor)
    tool_asks = truth != 0
    right = int((top[speaks] == truth[speaks]).sum())
    group_note = (
        f"CV at the floor: {int(speaks.sum())} dispatched, {right} right; "
        f"{int((speaks & tool_asks).sum())}/{int(tool_asks.sum())} tool asks covered."
    )
    head.fit(x, truth)
    GROUP_OUT.write_text(
        render_group_swift(GROUPS, head.coef_, head.intercept_, floor, len(items), group_note)
    )
    print(f"wrote {GROUP_OUT.relative_to(MACOS)}: floor {floor:.3f}; {group_note}")


if __name__ == "__main__":
    main()
