# /// script
# requires-python = ">=3.11"
# dependencies = ["numpy>=1.26", "scikit-learn>=1.5"]
# ///
"""Train M1K3's per-turn tool router and write its Swift weights.

    uv run tools/router/train_tool_router.py        # from macos/

A logistic layer over Apple's NLEmbedding sentence vectors: does this chat turn
need a tool? The threshold is picked by 5-fold cross-validation to keep 97% of
the training set's tool asks, because a miss hides a tool the turn needed. The
eval fixtures are the test set and never enter training (scratch/laya-spike,
FINDINGS round 3: 42/42 real tool asks kept, 28/74 no-tool turns freed).

Output: Sources/M1K3Chat/ToolNeedRouterWeights.swift (generated; do not edit).

Signed: Kev + claude-opus-5-5, 2026-09-26, Confidence 0.8 (the recipe is the
spike's, reproduced; the data is synthetic until a shadow log exists). Prior: Unknown.
"""
from __future__ import annotations

import json
import subprocess
import tempfile
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
MACOS = HERE.parents[1]
DATA = HERE / "data" / "tool_router_train.json"
OUT = MACOS / "Sources" / "M1K3Chat" / "ToolNeedRouterWeights.swift"
RECALL = 0.97
C = 4.0


def labels(items: list[dict]) -> np.ndarray:
    return np.array([item["group"] != "none" for item in items])


def normalise(vectors: np.ndarray) -> np.ndarray:
    return vectors / np.linalg.norm(vectors, axis=1, keepdims=True)


def recall_threshold(probabilities: np.ndarray, is_tool: np.ndarray, recall: float = RECALL) -> float:
    """The highest threshold that still keeps `recall` of the tool asks."""
    return float(np.quantile(probabilities[is_tool], 1.0 - recall))


def render_swift(weights: np.ndarray, bias: float, threshold: float, count: int, cv_note: str) -> str:
    rows = [", ".join(f"{w:.9g}" for w in weights[i : i + 8]) for i in range(0, len(weights), 8)]
    body = ",\n        ".join(rows)
    return f"""//
//  ToolNeedRouterWeights.swift
//  M1K3Chat
//
//  GENERATED by tools/router/train_tool_router.py; do not edit by hand.
//  A logistic layer over NLEmbedding's English sentence vector (L2-normalised):
//  P(this turn needs a tool). Trained on {count} synthetic labelled prompts
//  (tools/router/data); the eval fixtures are its test set.
//  {cv_note}
//

enum ToolNeedRouterWeights {{
    /// At or above: keep the tools. Picked to keep {RECALL:.0%} of tool asks in cross-validation.
    static let threshold: Double = {threshold:.9g}
    static let bias: Double = {bias:.9g}
    static let weights: [Double] = [
        {body},
    ]
}}
"""


def embed(prompts: list[str]) -> np.ndarray:
    with tempfile.TemporaryDirectory() as tmp:
        source, target = Path(tmp) / "in.json", Path(tmp) / "out.json"
        source.write_text(json.dumps(prompts))
        subprocess.run(["swift", str(HERE / "embed.swift"), str(source), str(target)], check=True)
        return np.array(json.loads(target.read_text()), dtype=np.float64)


def main() -> None:
    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import StratifiedKFold, cross_val_predict

    items = json.loads(DATA.read_text())["items"]
    x, y = normalise(embed([item["prompt"] for item in items])), labels(items)
    model = LogisticRegression(C=C, max_iter=5000, class_weight="balanced")
    folds = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
    cv = cross_val_predict(model, x, y, cv=folds, method="predict_proba")[:, 1]
    threshold = recall_threshold(cv, y)
    freed = int((cv[~y] < threshold).sum())
    note = f"CV at the threshold: {int((cv[y] >= threshold).sum())}/{int(y.sum())} tool asks kept, {freed}/{int((~y).sum())} chat turns freed."
    model.fit(x, y)
    OUT.write_text(render_swift(model.coef_[0], float(model.intercept_[0]), threshold, len(items), note))
    print(f"wrote {OUT.relative_to(MACOS)}: threshold {threshold:.3f}; {note}")


if __name__ == "__main__":
    main()
