package app.m1k3.ai.domain.chat.artifact

/**
 * ArtifactData — a self-contained HTML document generated by the model.
 *
 * Rendered in a sandboxed WebView with M1K3 design tokens injected as
 * CSS variables and the `window.Ma` JS bridge for native interactions.
 *
 * The model wraps artifacts in `<artifact>` tags (same convention as
 * Claude artifacts — behavioural transfer from existing prompt patterns):
 *
 * ```
 * <artifact id="pomodoro" type="html">
 *   <!DOCTYPE html>
 *   <html>...</html>
 * </artifact>
 * ```
 */
data class ArtifactData(
    /** Unique identifier from the model's artifact tag */
    val id: String,
    /** Content type — currently always "html" */
    val type: String = "html",
    /** The raw HTML content, trimmed */
    val html: String
)
