//
//  ToolNeedRouter.swift
//  M1K3Chat
//
//  Does this chat turn need a tool at all? Measured 2026-09-26 (live A/B, Mini,
//  22 chat fixtures, app quit): the same chat turn took a median 51.5 s with
//  the tool palette and 13.4 s without, and scored better without (13 → 15/22;
//  with tools Mini disowned "the capital of Australia"). So a turn the router
//  reads as plain chat skips the palette.
//
//  The router is a logistic layer (ToolNeedRouterWeights, generated by
//  tools/router/train_tool_router.py) over Apple's built-in English sentence
//  embedding: nothing downloaded, ~5 ms. The spike (scratch/laya-spike) tried
//  Laya, an MLX decision encoder, first: zero-shot it could not see web asks;
//  trained on the same labels, Apple's embedding matched it without a ~1 GB
//  model. On the eval fixtures, never trained on: 42/42 tool asks kept, 28/74
//  no-tool turns freed.
//
//  It fails OPEN. No vector (another language, no embedding asset), a vector of
//  the wrong size, or a non-finite score keeps the tools: hiding a tool the
//  turn needed is a wrong answer, keeping one it didn't is only slower.
//
//  Signed: Kev + claude-opus-5-5, 2026-09-26, Confidence 0.75 (pure and pinned;
//  the weights come from synthetic data until a shadow log grows real labels,
//  and the live gain is re-measured once the chat route is wired). Prior: Unknown.
//

import Foundation
import NaturalLanguage

public enum ToolNeedRouter {
    public enum Verdict: Sendable, Equatable {
        /// Offer the tool palette as today.
        case tools
        /// Plain chat: answer without the palette.
        case chat
    }

    /// P(needs a tool) for one sentence vector; nil when it can't be scored.
    public static func probability(_ vector: [Double]) -> Double? {
        let weights = ToolNeedRouterWeights.weights
        guard vector.count == weights.count else { return nil }
        let norm = vector.reduce(0) { $0 + $1 * $1 }.squareRoot()
        guard norm > 0, norm.isFinite else { return nil }
        var z = ToolNeedRouterWeights.bias
        for (value, weight) in zip(vector, weights) {
            z += value / norm * weight
        }
        let p = 1 / (1 + exp(-z))
        return p.isFinite ? p : nil
    }

    public static func verdict(probability: Double?) -> Verdict {
        guard let probability, probability.isFinite else { return .tools }
        return probability >= ToolNeedRouterWeights.threshold ? .tools : .chat
    }

    public static func verdict(for question: String, embed: (String) -> [Double]?) -> Verdict {
        verdict(probability: embed(question).flatMap(probability))
    }
}

/// Apple's English sentence embedding, abstaining on text that isn't English
/// (the weights only know that space). Loaded once; `NLEmbedding` is read-only.
public final class NLSentenceEmbedder: @unchecked Sendable {
    private let embedding = NLEmbedding.sentenceEmbedding(for: .english)
    private let lock = NSLock()

    public init() {}

    public func vector(_ text: String) -> [Double]? {
        guard let embedding else { return nil }
        let recognizer = NLLanguageRecognizer()
        recognizer.processString(text)
        guard recognizer.dominantLanguage == .english else { return nil }
        // NLEmbedding documents no thread-safety guarantee; turns are rare, so serialise.
        return lock.withLock { embedding.vector(for: text) }
    }
}
