//
//  ToolGroupRouter.swift
//  M1K3Chat
//
//  Which read-only tool does a tools-verdict turn want, read with no model in the
//  loop? ToolNeedRouter says a turn needs a tool; this head says which family (a
//  softmax over the router data's groups, ToolGroupRouterWeights, generated by
//  tools/router/train_tool_router.py over the same Apple sentence vector), and a
//  word check names the tool inside the family. The app then runs it (ToolDispatch)
//  exactly as it runs Apple's pick. Why: Apple's constrained pick costs ~1.2 s, and
//  where Apple's model isn't ready nothing picks, so the brain must write the call
//  itself (Lil on Qwen3.5 writes a malformed one without thinking).
//
//  It only speaks when it is sure. Below the floor (picked in cross-validation for
//  95% precision among the turns it would dispatch), on a `none` read (the two heads
//  disagree), or when the words inside a family don't single out one tool, it abstains
//  and the turn takes Apple's pick or the agent exactly as before. A wrong tool is a
//  wrong answer; an abstention is only slower.
//
//  An experiment, OFF by default (`toolGroupRouter`). ADR 0009's spike rejected picking
//  by group alone: at 95% precision it called "What's 17 × 23?" a device question, and
//  closed-vocabulary rules alone reached ~83% precision at 40% recall ("meeting notes"
//  are notes, not the calendar). Here a device pick needs both the group and one cue
//  word inside it ("17 × 23" names no device), every pick falls back to Apple's when
//  the head abstains, and only the router's tools verdict reaches it; the web, notes and
//  activity families still rest on the head alone. Whether that is precise enough is
//  the eval arm's call (`M1K3_SELFTEST_CHATEVAL_ROUTER=dispatch` + `_ROUTER_HEAD=1`).
//  The untrained stub has no groups and abstains on every turn.
//
//  Signed: Kev + claude-opus-5-5, 2026-10-07, Confidence 0.7 (pure and pinned; the
//  weights come from synthetic data and the live gain is the eval arm's to show).
//  Prior: Unknown.
//

import Foundation

public enum ToolGroupRouter {
    /// One trained head: `weights[i]` and `biases[i]` score `groups[i]`.
    public struct Head: Sendable {
        public let groups: [String]
        public let weights: [[Double]]
        public let biases: [Double]
        public let floor: Double

        public init(groups: [String], weights: [[Double]], biases: [Double], floor: Double) {
            self.groups = groups
            self.weights = weights
            self.biases = biases
            self.floor = floor
        }

        public static let shipping = Head(
            groups: ToolGroupRouterWeights.groups,
            weights: ToolGroupRouterWeights.weights,
            biases: ToolGroupRouterWeights.biases,
            floor: ToolGroupRouterWeights.floor
        )
    }

    /// The head's top group and its softmax probability.
    public struct Reading: Sendable, Equatable {
        public let group: String
        public let probability: Double
    }

    /// The top group for one sentence vector; nil when it can't be scored (no groups,
    /// a shape mismatch, a zero or non-finite vector), which is an abstention.
    public static func read(_ vector: [Double], head: Head = .shipping) -> Reading? {
        guard !head.groups.isEmpty,
              head.weights.count == head.groups.count, head.biases.count == head.groups.count,
              head.weights.allSatisfy({ $0.count == vector.count })
        else { return nil }
        let norm = vector.reduce(0) { $0 + $1 * $1 }.squareRoot()
        guard norm > 0, norm.isFinite else { return nil }
        let logits = zip(head.weights, head.biases).map { row, bias in
            zip(vector, row).reduce(bias) { $0 + $1.0 / norm * $1.1 }
        }
        guard let top = logits.max(), top.isFinite, let index = logits.firstIndex(of: top) else { return nil }
        let total = logits.reduce(0) { $0 + exp($1 - top) }
        let probability = 1 / total
        guard probability.isFinite else { return nil }
        return Reading(group: head.groups[index], probability: probability)
    }

    /// The tool to dispatch for this turn, or nil: the picker or the agent decides.
    public static func pick(for question: String, embed: (String) -> [Double]?, head: Head = .shipping) -> ToolPick? {
        guard let vector = embed(question), let reading = read(vector, head: head),
              reading.probability >= head.floor
        else { return nil }
        return pick(group: reading.group, question: question)
    }

    /// A family to the one tool its words name. An empty query means "use the user's
    /// words" (ToolDispatch.plan). nil where the words don't settle it.
    static func pick(group: String, question: String) -> ToolPick? {
        switch group {
        case "device":
            return deviceTool(question).map { ToolPick(tool: $0, query: "") }
        case "knowledge":
            return ToolPick(tool: "search_knowledge", query: "")
        case "activity":
            return ToolPick(tool: "recent_activity", query: "")
        case "web":
            if let url = ToolDispatch.webURL(question) {
                return ToolPick(tool: "fetch_page", query: url)
            }
            return ToolPick(tool: mentions(question, any: referenceCues) ? "lookup_fact" : "web_search", query: "")
        case "script":
            // Anything that acts is the agent's, with only the acting tools (#427).
            return ToolPick(tool: ToolPick.action, query: "")
        default:
            // `none` after a tools verdict, or a group this code doesn't know: the two
            // heads disagree, so neither decides.
            return nil
        }
    }

    /// The device family's tools and the words that name each. Exactly one tool must
    /// be named: "the time and my battery" names two and abstains.
    static let deviceCues: [(tool: String, cues: [String])] = [
        ("calendar_peek", ["calendar", "schedule", "agenda", "meeting", "meetings", "appointment", "appointments", "event", "events"]),
        ("battery_status", ["battery", "charge", "charging", "juice"]),
        ("system_status", ["cpu", "ram", "memory", "disk", "storage", "hard drive", "performance", "running slow", "system", "mac health"]),
        ("current_location", ["location", "where am i", "whereabouts"]),
        ("datetime", ["time", "date", "day", "clock"]),
    ]

    /// A reference lookup rather than a live search ("from a reference source").
    static let referenceCues = ["wikipedia", "encyclopedia", "encyclopaedia", "reference source", "reference book"]

    static func deviceTool(_ question: String) -> String? {
        let named = deviceCues.filter { mentions(question, any: $0.cues) }
        return named.count == 1 ? named[0].tool : nil
    }

    /// Whole-word (or whole-phrase) match, case-insensitive: "daytime" is not "day".
    static func mentions(_ text: String, any cues: [String]) -> Bool {
        let cleaned = String(text.lowercased().map { $0.isLetter || $0.isNumber ? $0 : " " })
        let words = " " + cleaned.split(separator: " ").joined(separator: " ") + " "
        return cues.contains { words.contains(" \($0) ") }
    }
}
