//
//  ToolGroupRouter.swift
//  M1K3Chat
//
//  Which read-only tool does a tools-verdict turn want, read with no model in the
//  loop? ToolNeedRouter says a turn needs a tool; this head says which family (a
//  softmax over the router data's groups, ToolGroupRouterWeights, generated by
//  tools/router/train_tool_router.py over the same Apple sentence vector), and a
//  word check names the tool inside the family. The app then runs it (ToolDispatch)
//  exactly as it runs Apple's pick. Why: Apple's constrained pick costs ~1.2 s, and
//  where Apple's model isn't ready nothing picks, so the brain must write the call
//  itself (Lil on Qwen3.5 writes a malformed one without thinking).
//
//  It only speaks when it is sure. Below the floor (picked in cross-validation for
//  95% precision among the turns it would dispatch), on a `none` read (the two heads
//  disagree), or when the words inside a family don't single out one tool, it abstains
//  and the turn takes Apple's pick or the agent exactly as before. A wrong tool is a
//  wrong answer; an abstention is only slower.
//
//  An experiment, OFF by default (`toolGroupRouter`). ADR 0009's spike rejected picking
//  by group alone: at 95% precision it called "What's 17 × 23?" a device question, and
//  closed-vocabulary rules alone reached ~83% precision at 40% recall ("meeting notes"
//  are notes, not the calendar). Here a device pick needs both the group and one cue
//  word inside it ("17 × 23" names no device), every pick falls back to Apple's when
//  the head abstains, and only the router's tools verdict reaches it. It never picks a
//  web tool (a wrong one is egress) or an action; the notes and activity families (local
//  reads) still rest on the head alone. Whether that is precise enough is
//  the eval arm's call (`M1K3_SELFTEST_CHATEVAL_ROUTER=dispatch` + `_ROUTER_HEAD=1`).
//  The untrained stub has no groups and abstains on every turn.
//
//  Signed: Kev + claude-opus-5-5, 2026-10-07, Confidence 0.7 (pure and pinned; the
//  weights come from synthetic data and the live gain is the eval arm's to show).
//  Prior: Unknown.
//
//  Review: Kev + claude-fable-5.1, 2026-10-09 — "schedule" is a cue only as a noun; a turn opening on it is a write (#512).
//  Review: same day, code-quality fold — the verb reading covers every position ("Can you schedule time with
//  Anna for the meeting?" matched "meeting"): "schedule" is the noun only after a lead word (`scheduleNounLeads`).
//  Review: Kev + claude-opus-5-5, 2026-10-10 — the knowledge and activity families abstain on a memory write
//  too (`memoryWriteCues`), as device did; the challenger on the flip found "forget what I told you" near the
//  floor. Confidence 0.85 (tests pin writes and reads).

import Foundation

public enum ToolGroupRouter {
    /// One trained head: `weights[i]` and `biases[i]` score `groups[i]`.
    public struct Head: Sendable {
        public let groups: [String]
        public let weights: [[Double]]
        public let biases: [Double]
        public let floor: Double

        public init(groups: [String], weights: [[Double]], biases: [Double], floor: Double) {
            self.groups = groups
            self.weights = weights
            self.biases = biases
            self.floor = floor
        }

        public static let shipping = Head(
            groups: ToolGroupRouterWeights.groups,
            weights: ToolGroupRouterWeights.weights,
            biases: ToolGroupRouterWeights.biases,
            floor: ToolGroupRouterWeights.floor
        )
    }

    /// The head's top group and its softmax probability.
    public struct Reading: Sendable, Equatable {
        public let group: String
        public let probability: Double
    }

    /// The top group for one sentence vector; nil when it can't be scored (no groups,
    /// a shape mismatch, a zero or non-finite vector), which is an abstention.
    public static func read(_ vector: [Double], head: Head = .shipping) -> Reading? {
        guard !head.groups.isEmpty,
              head.weights.count == head.groups.count, head.biases.count == head.groups.count,
              head.weights.allSatisfy({ $0.count == vector.count })
        else { return nil }
        let norm = vector.reduce(0) { $0 + $1 * $1 }.squareRoot()
        guard norm > 0, norm.isFinite else { return nil }
        let logits = zip(head.weights, head.biases).map { row, bias in
            zip(vector, row).reduce(bias) { $0 + $1.0 / norm * $1.1 }
        }
        guard let top = logits.max(), top.isFinite, let index = logits.firstIndex(of: top) else { return nil }
        let total = logits.reduce(0) { $0 + exp($1 - top) }
        let probability = 1 / total
        guard probability.isFinite else { return nil }
        return Reading(group: head.groups[index], probability: probability)
    }

    /// The tool to dispatch for this turn, or nil: the picker or the agent decides.
    /// `chain`: a device turn naming two tools ("the time and my battery") runs both.
    public static func pick(
        for question: String, embed: (String) -> [Double]?, head: Head = .shipping, chain: Bool = false
    ) -> ToolPick? {
        guard let vector = embed(question), let reading = read(vector, head: head),
              reading.probability >= head.floor
        else { return nil }
        return pick(group: reading.group, question: question, chain: chain)
    }

    /// A family to the tool its words name. An empty query means "use the user's
    /// words" (ToolDispatch.plan). nil where the words don't settle it.
    static func pick(group: String, question: String, chain: Bool = false) -> ToolPick? {
        switch group {
        case "device":
            let tools = deviceTools(question)
            guard let first = tools.first, tools.count == 1 || chain && tools.count <= ToolDispatch.maxChain else {
                return nil
            }
            return ToolPick(tool: first, query: "", then: tools.dropFirst().map { ToolPick(tool: $0, query: "") })
        case "knowledge":
            return memoryWrite(question) ? nil : ToolPick(tool: "search_knowledge", query: "")
        case "activity":
            return memoryWrite(question) ? nil : ToolPick(tool: "recent_activity", query: "")
        default:
            // `none` after a tools verdict (the two heads disagree); `web` (a wrong pick there
            // sends the user's words off the device, so Apple's pick keeps that call: #510
            // review); `script` (the thinnest class, and a wrong read would strip the read-only
            // tools from the agent turn: Apple's pick can still say `action`); or a group this
            // code doesn't know.
            return nil
        }
    }

    /// The device family's tools and the words that name each. One named tool picks it;
    /// "the time and my battery" names two, a chain when chains are on, else an abstention.
    static let deviceCues: [(tool: String, cues: [String])] = [
        // Not a bare "event(s)": "current events" is news (#510 review 2).
        ("calendar_peek", [
            // "schedule" only as a noun: "schedule lunch with Sean" is a write (#510 review 3).
            "calendar", "my schedule", "the schedule", "schedule for", "schedule today", "agenda",
            "meeting", "meetings", "appointment", "appointments",
            "my events", "any events", "my day",
        ]),
        ("battery_status", ["battery", "charging", "juice"]),
        ("system_status", [
            "cpu", "ram", "memory usage", "memory use", "memory status", "disk", "storage", "hard drive",
            "performance", "running slow", "system resources", "system status", "mac health",
        ]),
        ("current_location", ["location", "where am i", "whereabouts"]),
        // Not a bare "time" or "date": "the last time we met", "the due date for my taxes"
        // are no clock read (#510 review).
        ("datetime", [
            "what time", "the time", "current time", "time now", "time check", "time is it",
            "the date", "what date", "current date", "date and time", "date today", "what day", "which day", "clock",
        ]),
    ]

    /// A device read is a READ: "schedule a meeting", "add an event", "set a reminder"
    /// write, and the calendar peek would answer them with a list (and the brain might
    /// say it booked it). Any of these words abstains.
    static let writeCues = [
        "add", "create", "book", "set", "cancel", "move", "remind", "delete", "remove", "reschedule", "invite", "put",
    ]

    /// The read-only families' write words: "remember that…", "forget what I told you", "save
    /// this to my notes" would be answered with a read. Abstaining hands them to Apple's pick,
    /// which can still say `action` (the challenger on the flip, 2026-10-10: "forget what I told
    /// you about my address" read activity at 0.679). A bare "note" stays a read ("what did I
    /// note about…"); "note that" is the write.
    static let memoryWriteCues = writeCues + [
        "remember", "forget", "save", "store", "erase", "note that", "write down", "jot",
    ]

    static func memoryWrite(_ question: String) -> Bool {
        mentions(question, any: memoryWriteCues)
    }

    /// The words after which "schedule" is the noun ("my schedule", "today's schedule"). After
    /// anything else — the turn's first word, "you", "please", "to" — it is the verb, a write
    /// ("Can you schedule time with Anna for the meeting?" names a meeting and books one).
    static let scheduleNounLeads: Set<Substring> = [
        "my", "the", "your", "our", "his", "her", "their", "this", "that", "s",
        "today", "tomorrow", "work", "whole", "full", "daily", "weekly",
    ]

    /// "schedule" used as a verb anywhere in the turn (#510 review 3).
    static func schedulesSomething(_ question: String) -> Bool {
        let words = words(question)
        return words.indices.contains { i in
            words[i] == "schedule" && (i == words.startIndex || !scheduleNounLeads.contains(words[i - 1]))
        }
    }

    /// Every device tool the words name, in `deviceCues` order; none for a write.
    static func deviceTools(_ question: String) -> [String] {
        guard !schedulesSomething(question), !mentions(question, any: writeCues) else { return [] }
        return deviceCues.filter { mentions(question, any: $0.cues) }.map { $0.tool }
    }

    /// Whole-word (or whole-phrase) match, case-insensitive: "daytime" is not "day".
    static func mentions(_ text: String, any cues: [String]) -> Bool {
        let joined = " " + words(text).joined(separator: " ") + " "
        return cues.contains { joined.contains(" \($0) ") }
    }

    /// The turn's lower-cased words: letters and digits only ("today's" is "today", "s").
    static func words(_ text: String) -> [Substring] {
        String(text.lowercased().map { $0.isLetter || $0.isNumber ? $0 : " " }).split(separator: " ")
    }
}
