//
//  ToolGroupRouterWeights.swift
//  M1K3Chat
//
//  GENERATED by tools/router/train_tool_router.py; do not edit by hand.
//  A softmax layer over NLEmbedding's English sentence vector (L2-normalised):
//  which tool family a tools-verdict turn wants (ToolGroupRouter).
//  UNTRAINED: no groups, so the head abstains on every turn. Run the trainer on a Mac; the eval fixtures are its test set.
//  Not yet trained: the stub ships so the code compiles and stays byte-identical until a Mac run.
//

enum ToolGroupRouterWeights {
    /// Row order of `weights` and `biases`.
    static let groups: [String] = []
    /// At or above (top probability): dispatch. Picked for 95% precision in cross-validation.
    static let floor: Double = 1
    static let biases: [Double] = []
    static let weights: [[Double]] = [
    ]
}
