//
//  ToolNeedRouter.swift
//  M1K3Chat
//
//  Does this chat turn need a tool at all? Measured 2026-09-26 (live A/B, Mini,
//  22 chat fixtures, app quit): the same chat turn took a median 51.5 s with
//  the tool palette and 13.4 s without, and scored better without (13 → 15/22;
//  with tools Mini disowned "the capital of Australia"). So a turn the router
//  reads as plain chat skips the palette.
//
//  The router is a logistic layer (ToolNeedRouterWeights, generated by
//  tools/router/train_tool_router.py) over Apple's built-in English sentence
//  embedding: nothing downloaded, ~5 ms. The spike (scratch/laya-spike) tried
//  Laya, an MLX decision encoder, first: zero-shot it could not see web asks;
//  trained on the same labels, Apple's embedding matched it without a ~1 GB
//  model. On the eval fixtures, never trained on: 42/42 tool asks kept, 28/74
//  no-tool turns freed.
//
//  It fails OPEN. No vector (another language, no embedding asset), a vector of
//  the wrong size, or a non-finite score keeps the tools: hiding a tool the
//  turn needed is a wrong answer, keeping one it didn't is only slower. Short
//  turns skip the language guess, which is noise under ~24 characters.
//
//  Signed: Kev + claude-opus-5-5, 2026-09-26, Confidence 0.75 (pure and pinned;
//  the weights come from synthetic data until a shadow log grows real labels,
//  and the live gain is re-measured once the chat route is wired). Prior: Unknown.
//  Review: Kev + claude-opus-5-5, 2026-09-26 — challenger review: the strict
//  dominant-language gate failed "hi" (Catalan), "lol" (Dutch) and "ok cool" (Polish)
//  open to the palette. Short turns now skip the guess. Confidence 0.8.
//

import Foundation
import M1K3Inference
import NaturalLanguage

public enum ToolNeedRouter {
    public enum Verdict: Sendable, Equatable {
        /// Offer the tool palette as today.
        case tools
        /// Plain chat: answer without the palette.
        case chat
    }

    /// P(needs a tool) for one sentence vector; nil when it can't be scored.
    public static func probability(_ vector: [Double]) -> Double? {
        let weights = ToolNeedRouterWeights.weights
        guard vector.count == weights.count else { return nil }
        let norm = vector.reduce(0) { $0 + $1 * $1 }.squareRoot()
        guard norm > 0, norm.isFinite else { return nil }
        var z = ToolNeedRouterWeights.bias
        for (value, weight) in zip(vector, weights) {
            z += value / norm * weight
        }
        let p = 1 / (1 + exp(-z))
        return p.isFinite ? p : nil
    }

    public static func verdict(probability: Double?) -> Verdict {
        guard let probability, probability.isFinite else { return .tools }
        return probability >= ToolNeedRouterWeights.threshold ? .tools : .chat
    }

    public static func verdict(for question: String, embed: (String) -> [Double]?) -> Verdict {
        decide(for: question, embed: embed).verdict
    }

    /// The verdict with the score behind it (nil when it couldn't be scored), so
    /// a caller can log what the router saw: those lines are future labels.
    public struct Decision: Sendable, Equatable {
        public let verdict: Verdict
        public let probability: Double?

        public init(verdict: Verdict, probability: Double?) {
            self.verdict = verdict
            self.probability = probability
        }
    }

    public static func decide(for question: String, embed: (String) -> [Double]?) -> Decision {
        let p = embed(question).flatMap(probability)
        return Decision(verdict: verdict(probability: p), probability: p)
    }
}

/// How a turn the router reads as plain chat is answered: `decide` is the
/// router, `instructions` the persona for the plain generation (nil keeps the
/// provider's own, which on Mini is the prewarmed one).
public struct PlainTurnRoute: Sendable {
    public let decide: @Sendable (String) -> ToolNeedRouter.Decision
    public let instructions: String?

    public init(decide: @escaping @Sendable (String) -> ToolNeedRouter.Decision, instructions: String?) {
        self.decide = decide
        self.instructions = instructions
    }
}

/// The plain turn replays history as `USER:` / `M1K3:` lines, and a small model
/// may answer in that transcript voice, so the label is cut from the answer.
/// Providers stream either cumulative snapshots (AFM) or deltas (MLX): `ingest`
/// folds either into the whole answer so far, and yields the cleaned WHOLE text
/// each time it grows, so every yield extends the last and a held first piece
/// ("M", which might have become the label) is never lost (code review).
public struct PlainTurnStream {
    static let label = "M1K3:"
    private var raw = ""
    private var sent = ""

    public init() {}

    /// One provider chunk in; the cleaned answer so far when it grew, else nil.
    public mutating func ingest(_ chunk: String) -> String? {
        raw = StreamFold.fold(current: raw, chunk: chunk)
        guard let clean = Self.clean(raw), clean.count > sent.count, clean.hasPrefix(sent) else { return nil }
        sent = clean
        return clean
    }

    // The label cut from a WHOLE answer so far; nil while it could still become the label.

    public static func clean(_ snapshot: String) -> String? {
        let text = snapshot.drop(while: \.isWhitespace)
        if label.hasPrefix(text) { return nil }
        guard text.hasPrefix(label) else { return String(text) }
        let rest = text.dropFirst(label.count).drop(while: \.isWhitespace)
        return rest.isEmpty ? nil : String(rest)
    }
}

/// Apple's English sentence embedding, abstaining on text that isn't English
/// (the weights only know that space). Loaded once; `NLEmbedding` is read-only.
public final class NLSentenceEmbedder: @unchecked Sendable {
    private let embedding = NLEmbedding.sentenceEmbedding(for: .english)
    private let lock = NSLock()

    public init() {}

    public func vector(_ text: String) -> [Double]? {
        guard let embedding, Self.readsAsEnglish(text) else { return nil }
        // NLEmbedding documents no thread-safety guarantee; turns are rare, so serialise.
        return lock.withLock { embedding.vector(for: text) }
    }

    /// Too little text for a language guess ("hi" reads as Catalan, "lol" as Dutch)
    /// is taken as English; longer text abstains only when English is clearly unlikely.
    static func readsAsEnglish(_ text: String) -> Bool {
        guard text.count >= shortTurnLength else { return true }
        let recognizer = NLLanguageRecognizer()
        recognizer.processString(text)
        if recognizer.dominantLanguage == .english { return true }
        return (recognizer.languageHypotheses(withMaximum: 3)[.english] ?? 0) >= 0.2
    }

    static let shortTurnLength = 24
}
