package app.m1k3.ai.assistant.utils

import co.touchlab.kermit.Logger as KermitLogger
import co.touchlab.kermit.Severity
import co.touchlab.kermit.StaticConfig
import co.touchlab.kermit.platformLogWriter

/**
 * 間 AI Logging Utility
 *
 * Multiplatform logging using Kermit.
 * Provides structured, tagged logging across all platforms.
 *
 * Benefits:
 * - ✅ Multiplatform (Android, iOS, JVM, JS, WASM)
 * - ✅ Structured logging with tags
 * - ✅ Log levels (verbose, debug, info, warn, error)
 * - ✅ Production-ready (can disable debug logs in release builds)
 * - ✅ Better than println (filterable, searchable, platform-native)
 *
 * Usage:
 * ```kotlin
 * class ChatViewModel {
 *     private val logger = Logger.withTag("ChatViewModel")
 *
 *     fun sendMessage(text: String) {
 *         logger.d { "Sending message: $text" }
 *         // ... send logic
 *         logger.i { "Message sent successfully" }
 *     }
 *
 *     fun onError(error: Exception) {
 *         logger.e(error) { "Failed to send message" }
 *     }
 * }
 * ```
 */
object Logger {
    /**
     * Base logger instance
     *
     * Uses platform-specific log writers:
     * - Android: Logcat
     * - iOS: NSLog
     * - JVM: System.out
     * - JS: console.log
     */
    private val baseLogger = KermitLogger(
        config = StaticConfig(
            minSeverity = if (BuildConfig.DEBUG) Severity.Verbose else Severity.Info
        ),
        tag = "MaAI"
    )

    /**
     * Create tagged logger for specific component
     *
     * @param tag Component tag (e.g., "ChatViewModel", "Avatar3DEngine")
     * @return Tagged logger instance
     */
    fun withTag(tag: String): KermitLogger {
        return baseLogger.withTag(tag)
    }

    /**
     * Global logger for untagged logs
     *
     * @deprecated Use withTag() for better log organization
     */
    @Deprecated("Use withTag() for better log organization")
    fun v(message: String) = baseLogger.v { message }

    @Deprecated("Use withTag() for better log organization")
    fun d(message: String) = baseLogger.d { message }

    @Deprecated("Use withTag() for better log organization")
    fun i(message: String) = baseLogger.i { message }

    @Deprecated("Use withTag() for better log organization")
    fun w(message: String) = baseLogger.w { message }

    @Deprecated("Use withTag() for better log organization")
    fun e(throwable: Throwable? = null, message: String) = baseLogger.e(throwable) { message }
}

/**
 * BuildConfig placeholder
 *
 * In production, this should be generated by build system.
 * For now, always enable debug logging.
 */
object BuildConfig {
    const val DEBUG = true
}

/**
 * Usage Examples:
 * ```kotlin
 * // ===== In ViewModel =====
 * class ChatViewModel : ViewModel() {
 *     private val logger = Logger.withTag("ChatViewModel")
 *
 *     fun loadMessages() {
 *         logger.d { "Loading messages for project: $projectId" }
 *         // ... load logic
 *         logger.i { "Loaded ${messages.size} messages" }
 *     }
 *
 *     fun onError(error: Exception) {
 *         logger.e(error) { "Failed to load messages" }
 *     }
 * }
 *
 * // ===== In Repository =====
 * class ConversationRepository(private val database: Database) {
 *     private val logger = Logger.withTag("ConversationRepo")
 *
 *     suspend fun saveMessage(message: Message) {
 *         logger.v { "Saving message: ${message.id}" }
 *         database.messageQueries.insert(message)
 *         logger.d { "Message saved successfully" }
 *     }
 * }
 *
 * // ===== In AI Engine =====
 * class LlamaCppEngine : BaseLlmEngine {
 *     private val logger = Logger.withTag("LlamaCppEngine")
 *
 *     override suspend fun generate(prompt: String): String {
 *         logger.i { "Generating response for ${prompt.length} chars" }
 *         val start = System.currentTimeMillis()
 *         // ... generation
 *         val duration = System.currentTimeMillis() - start
 *         logger.d { "Generated ${response.length} chars in ${duration}ms" }
 *         return response
 *     }
 * }
 *
 * // ===== In Avatar System =====
 * class Avatar3DEngine {
 *     private val logger = Logger.withTag("Avatar3D")
 *
 *     fun playAnimation(name: String) {
 *         logger.v { "Playing animation: $name" }
 *         // ... animation logic
 *     }
 *
 *     fun onAnimationComplete(name: String) {
 *         logger.d { "Animation complete: $name" }
 *     }
 * }
 * ```
 */
