#!/bin/bash
# ci_post_clone.sh — Xcode Cloud post-clone hook for M1K3 (macOS)
#
# THE M1K3-CRITICAL STEP: M1K3's pbxproj is GITIGNORED (generated by xcodegen
# from macos/project.yml), so Xcode Cloud clones a repo with NO .xcodeproj.
# This hook regenerates the project BEFORE resolving SPM — without it the build
# has nothing to compile. (the prior knowledge-server project commits its pbxproj and skips this; M1K3 can't.)
#
# Xcode Cloud finds ci_scripts/ because it sits next to macos/M1K3.xcodeproj.
set -euo pipefail

echo "=== M1K3 CI: Post-Clone ==="
xcodebuild -version | head -1
swift --version | head -1

MACOS_DIR="$CI_PRIMARY_REPOSITORY_PATH/macos"

# 1. Tooling — Xcode Cloud images ship Homebrew. Pin it down so a flaky
# formulae.brew.sh fetch can't sink the build (build 57 timed out there after
# 300s): skip the network-heavy auto-update, RETRY the install, then HARD-CHECK
# xcodegen is on PATH — otherwise `set -e` + a bare `xcodegen` below fails with a
# cryptic exit 127 ("command not found") instead of this clear, retryable message.
export HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_ENV_HINTS=1 HOMEBREW_NO_INSTALL_CLEANUP=1
echo "--- Installing xcodegen (essential)…"
for attempt in 1 2 3; do
  command -v xcodegen >/dev/null 2>&1 && break
  brew install xcodegen || true
  command -v xcodegen >/dev/null 2>&1 && break
  echo "⚠️  xcodegen not yet available (attempt $attempt/3) — retrying in 15s…"
  sleep 15
done
command -v xcodegen >/dev/null 2>&1 || {
  echo "❌ xcodegen unavailable after 3 attempts — Homebrew (formulae.brew.sh) is"
  echo "   unreachable on this runner. This is transient infra, not a code failure:"
  echo "   re-run the build."
  exit 1
}
# xcbeautify is cosmetic — the test step below falls back to raw output without it.
echo "--- Installing xcbeautify (cosmetic, best-effort)…"
brew install xcbeautify || echo "    (xcbeautify unavailable — raw swift test output)"

# 2. Generate M1K3.xcodeproj from project.yml (the gitignored artifact).
echo "--- Generating M1K3.xcodeproj from project.yml..."
cd "$MACOS_DIR"
xcodegen generate

# 3. Seed the committed lockfile into the freshly-generated project.
# Xcode Cloud disables automatic package resolution and requires a committed
# Package.resolved. Ours can't live in the (gitignored) .xcodeproj, so it's
# committed at macos/Package.resolved and copied into the workspace here — else
# resolution fails with exit 74 ("a resolved file is required…") the moment a
# new dependency (e.g. onnxruntime) isn't in the project's lock.
echo "--- Seeding committed Package.resolved into the generated workspace..."
RESOLVED_SRC="$MACOS_DIR/Package.resolved"
RESOLVED_DST="$MACOS_DIR/M1K3.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
if [ -f "$RESOLVED_SRC" ]; then
  mkdir -p "$(dirname "$RESOLVED_DST")"
  cp "$RESOLVED_SRC" "$RESOLVED_DST"
  echo "    seeded $RESOLVED_DST"
else
  echo "⚠️  $RESOLVED_SRC missing — resolution may fail under Xcode Cloud's locked mode."
fi

# 4. Resolve SPM packages — Xcode Cloud starts with empty DerivedData.
echo "--- Resolving Swift packages..."
xcodebuild -resolvePackageDependencies \
  -scheme M1K3 \
  -project "$MACOS_DIR/M1K3.xcodeproj"

# 5. THE DEPLOY GATE: run the FULL SwiftPM test suite before anything is archived.
# WHY HERE and not an Xcode Cloud "Test" action: the app scheme's <Testables> is
# EMPTY — the package's test targets aren't scheme-testable, so a Test action runs
# ZERO tests (a hollow green gate). `swift test` instead AUTO-DISCOVERS every test
# target in Package.swift (the same invocation the PR CI uses), so the gate stays
# correct with no hand-maintained target list — including when new targets land
# (e.g. an incoming M1K3Preview). A failure here exits non-zero, which FAILS the
# whole Xcode Cloud build run, so Archive never runs and no red build reaches
# TestFlight. Emergency bypass: set CI_SKIP_TESTS=1 on the workflow (archive-only).
#
# This is the single source of the "successful test gate" — the Release workflow
# is therefore just Archive→TestFlight (no separate, hollow Test action). See
# docs/XCODE_CLOUD_RELEASE.md.
if [ "${CI_SKIP_TESTS:-0}" = "1" ]; then
  echo "--- ⚠ CI_SKIP_TESTS=1 — skipping the full-suite deploy gate (archive-only run)"
else
  echo "--- Running the FULL SwiftPM test suite (deploy gate)…"
  # Match ci.yml EXACTLY: --parallel for speed, and M1K3_MLX_INTEGRATION=0 so the
  # MLX/Metal + WhisperKit integration tests stay OFF — they only run from a
  # bundled .app ("metallib wall"), and Xcode Cloud VMs may lack a usable Metal
  # GPU, so leaving them on would false-fail the gate. (On-device coverage is the
  # §4 post-archive MLX smoke, not this CLI suite.)
  export M1K3_MLX_INTEGRATION="0"
  if command -v xcbeautify >/dev/null 2>&1; then
    swift test --package-path "$MACOS_DIR" --parallel 2>&1 | xcbeautify
  else
    swift test --package-path "$MACOS_DIR" --parallel
  fi
  echo "--- ✓ Full suite GREEN — safe to archive + deploy"
fi

echo "=== Post-Clone Complete ✓ ==="
