#!/bin/bash
# ci_post_clone.sh — Xcode Cloud post-clone hook for M1K3 (macOS)
#
# THE M1K3-CRITICAL STEP: M1K3's pbxproj is GITIGNORED (generated by xcodegen
# from macos/project.yml), so Xcode Cloud clones a repo with NO .xcodeproj.
# This hook regenerates the project BEFORE resolving SPM — without it the build
# has nothing to compile. (the prior knowledge-server app commits its pbxproj and skips this; M1K3 can't.)
#
# Xcode Cloud finds ci_scripts/ because it sits next to macos/M1K3.xcodeproj.
set -euo pipefail

echo "=== M1K3 CI: Post-Clone ==="
xcodebuild -version | head -1
swift --version | head -1

MACOS_DIR="$CI_PRIMARY_REPOSITORY_PATH/macos"

# 1. Tooling — xcodegen WITHOUT Homebrew.
# Xcode Cloud's macOS-27-beta image has NO route to formulae.brew.sh (build 59:
# curl exit 7, "Couldn't connect" in ~4ms) and Homebrew can't resolve a bottle
# for the beta platform ("arm64_dunno"), so `brew install xcodegen` is impossible
# here. But github.com IS reachable (the repo cloned, and SPM resolves its deps
# from it), so fetch xcodegen's prebuilt release binary straight from GitHub and
# run it in place — no Homebrew in the path at all. Pinned for reproducibility;
# bump deliberately. (xcbeautify is dropped — it was cosmetic; step 5 falls back
# to raw swift-test output without it.)
XCODEGEN_VERSION="2.45.4"
TOOLS_DIR="$CI_PRIMARY_REPOSITORY_PATH/.ci-tools"
XCODEGEN="$TOOLS_DIR/xcodegen/bin/xcodegen"
echo "--- Fetching xcodegen $XCODEGEN_VERSION from GitHub (Homebrew is unreachable on this image)…"
mkdir -p "$TOOLS_DIR"
curl -fsSL --retry 3 --retry-delay 5 -o "$TOOLS_DIR/xcodegen.zip" \
  "https://github.com/yonaskolb/XcodeGen/releases/download/$XCODEGEN_VERSION/xcodegen.zip"
unzip -q -o "$TOOLS_DIR/xcodegen.zip" -d "$TOOLS_DIR"
chmod +x "$XCODEGEN"
"$XCODEGEN" --version || { echo "❌ xcodegen $XCODEGEN_VERSION failed to run on this image"; exit 1; }

# 2. Generate M1K3.xcodeproj from project.yml (the gitignored artifact).
echo "--- Generating M1K3.xcodeproj from project.yml..."
cd "$MACOS_DIR"
"$XCODEGEN" generate

# 3. Seed the committed lockfile into the freshly-generated project.
# Xcode Cloud disables automatic package resolution and requires a committed
# Package.resolved. Ours can't live in the (gitignored) .xcodeproj, so it's
# committed at macos/Package.resolved and copied into the workspace here — else
# resolution fails with exit 74 ("a resolved file is required…") the moment a
# new dependency (e.g. onnxruntime) isn't in the project's lock.
echo "--- Seeding committed Package.resolved into the generated workspaces..."
RESOLVED_SRC="$MACOS_DIR/Package.resolved"
# Two containers need the lockfile under Xcode Cloud's locked-resolution mode:
#  • the Archive action builds the app via M1K3.xcodeproj (its internal workspace)
#  • the Test action builds via the committed M1K3.xcworkspace (the package-test
#    scheme M1K3-Tests lives there — the app project can't reference package test
#    targets, so the workspace is the testing container). Miss either → exit 74.
RESOLVED_DSTS=(
  "$MACOS_DIR/M1K3.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
  "$MACOS_DIR/M1K3.xcworkspace/xcshareddata/swiftpm/Package.resolved"
)
if [ -f "$RESOLVED_SRC" ]; then
  for RESOLVED_DST in "${RESOLVED_DSTS[@]}"; do
    mkdir -p "$(dirname "$RESOLVED_DST")"
    cp "$RESOLVED_SRC" "$RESOLVED_DST"
    echo "    seeded $RESOLVED_DST"
  done
else
  echo "⚠️  $RESOLVED_SRC missing — resolution may fail under Xcode Cloud's locked mode."
fi

# 4. Resolve SPM packages — Xcode Cloud starts with empty DerivedData.
echo "--- Resolving Swift packages..."
xcodebuild -resolvePackageDependencies \
  -scheme M1K3 \
  -project "$MACOS_DIR/M1K3.xcodeproj"

# 4b. SCHEME-DRIFT GUARD: the native Test action (Xcode Cloud) runs the test
# targets hand-listed in the M1K3-Tests package scheme — xcodegen/the app
# project CAN'T reference package test targets, so that list is the source of
# truth for what gets tested. If a `.testTarget` lands in Package.swift but not
# the scheme, its tests would silently never run (a hollow-green gate). This
# fails the build loudly on any such drift. Cheap, no build. (Also enforced on
# PRs in ci.yml, so this rarely fires here — defence in depth.)
echo "--- Checking M1K3-Tests scheme covers every package test target…"
python3 "$MACOS_DIR/tools/ci/check_test_scheme.py"

# 5. THE DEPLOY GATE: run the FULL SwiftPM test suite before anything is archived.
# WHY HERE and not an Xcode Cloud "Test" action: the app scheme's <Testables> is
# EMPTY — the package's test targets aren't scheme-testable, so a Test action runs
# ZERO tests (a hollow green gate). `swift test` instead AUTO-DISCOVERS every test
# target in Package.swift (the same invocation the PR CI uses), so the gate stays
# correct with no hand-maintained target list — including when new targets land
# (e.g. an incoming M1K3Preview). A failure here exits non-zero, which FAILS the
# whole Xcode Cloud build run, so Archive never runs and no red build reaches
# TestFlight. Emergency bypass: set CI_SKIP_TESTS=1 on the workflow (archive-only).
#
# This is the single source of the "successful test gate" — the Release workflow
# is therefore just Archive→TestFlight (no separate, hollow Test action). See
# docs/XCODE_CLOUD_RELEASE.md.
if [ "${CI_SKIP_TESTS:-0}" = "1" ]; then
  echo "--- ⚠ CI_SKIP_TESTS=1 — skipping the full-suite deploy gate (archive-only run)"
else
  echo "--- Running the FULL SwiftPM test suite (deploy gate)…"
  # Match ci.yml EXACTLY: --parallel for speed, and M1K3_MLX_INTEGRATION=0 so the
  # MLX/Metal + WhisperKit integration tests stay OFF — they only run from a
  # bundled .app ("metallib wall"), and Xcode Cloud VMs may lack a usable Metal
  # GPU, so leaving them on would false-fail the gate. (On-device coverage is the
  # §4 post-archive MLX smoke, not this CLI suite.)
  export M1K3_MLX_INTEGRATION="0"
  if command -v xcbeautify >/dev/null 2>&1; then
    swift test --package-path "$MACOS_DIR" --parallel 2>&1 | xcbeautify
  else
    swift test --package-path "$MACOS_DIR" --parallel
  fi
  echo "--- ✓ Full suite GREEN — safe to archive + deploy"
fi

echo "=== Post-Clone Complete ✓ ==="
