#!/bin/bash
# ci_post_clone.sh — Xcode Cloud post-clone hook for M1K3 (macOS)
#
# THE M1K3-CRITICAL STEP: M1K3's pbxproj is GITIGNORED (generated by xcodegen
# from macos/project.yml), so Xcode Cloud clones a repo with NO .xcodeproj.
# This hook regenerates the project BEFORE resolving SPM — without it the build
# has nothing to compile. (the prior knowledge-server project commits its pbxproj and skips this; M1K3 can't.)
#
# Xcode Cloud finds ci_scripts/ because it sits next to macos/M1K3.xcodeproj.
set -euo pipefail

echo "=== M1K3 CI: Post-Clone ==="
xcodebuild -version | head -1
swift --version | head -1

MACOS_DIR="$CI_PRIMARY_REPOSITORY_PATH/macos"

# 1. Tooling — Xcode Cloud images ship Homebrew.
echo "--- Installing xcodegen + xcbeautify..."
brew install xcodegen xcbeautify || true

# 2. Generate M1K3.xcodeproj from project.yml (the gitignored artifact).
echo "--- Generating M1K3.xcodeproj from project.yml..."
cd "$MACOS_DIR"
xcodegen generate

# 3. Seed the committed lockfile into the freshly-generated project.
# Xcode Cloud disables automatic package resolution and requires a committed
# Package.resolved. Ours can't live in the (gitignored) .xcodeproj, so it's
# committed at macos/Package.resolved and copied into the workspace here — else
# resolution fails with exit 74 ("a resolved file is required…") the moment a
# new dependency (e.g. onnxruntime) isn't in the project's lock.
echo "--- Seeding committed Package.resolved into the generated workspace..."
RESOLVED_SRC="$MACOS_DIR/Package.resolved"
RESOLVED_DST="$MACOS_DIR/M1K3.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
if [ -f "$RESOLVED_SRC" ]; then
  mkdir -p "$(dirname "$RESOLVED_DST")"
  cp "$RESOLVED_SRC" "$RESOLVED_DST"
  echo "    seeded $RESOLVED_DST"
else
  echo "⚠️  $RESOLVED_SRC missing — resolution may fail under Xcode Cloud's locked mode."
fi

# 4. Resolve SPM packages — Xcode Cloud starts with empty DerivedData.
echo "--- Resolving Swift packages..."
xcodebuild -resolvePackageDependencies \
  -scheme M1K3 \
  -project "$MACOS_DIR/M1K3.xcodeproj"

echo "=== Post-Clone Complete ✓ ==="
