//
//  EmbeddingGemma2ReferenceTests.swift
//  M1K3MLXTests
//
//  Pins the EmbeddingGemma 2 reference fixture the Swift port (Stream C) will be
//  checked against: vectors from mlx-vlm on mlx-community/embeddinggemma-2-8bit,
//  generated by tools/weights/make_embeddinggemma2_reference.py. Pure — no MLX:
//  this guards the FIXTURE (unit norms, MRL-512 truncation, the <bos>…<eos>
//  wrapping, the prompts, relevance order), so the port's own test can trust it.
//
//  Signed: Kev + claude-opus-5-5, 2026-10-06, Confidence 0.85, Prior: none (new
//  file; GEMMA_1_1_PLAN Stream C, slice 1).
//  Review: Kev + claude-fable-5.1, 2026-10-10 (#545) — the fixture gained `d-long` (1,396 tokens,
//  past the 512 sliding window) and `q-long`; `longCasePresent` pins it so the port's local mask stays covered.

import Foundation
import Testing

struct EmbeddingGemma2ReferenceTests {
    struct Reference: Decodable {
        struct Case: Decodable {
            let id: String
            let role: String
            let prompted: String
            let inputIDs: [Int]
            let embedding768: [Double]
            let embedding512: [Double]
        }

        struct Ranking: Decodable {
            let query: String
            let ok: Bool
        }

        let model: String
        let modelRevision: String
        let prompts: [String: String]
        let cases: [Case]
        let rankingChecks: [Ranking]
    }

    private func load() throws -> Reference {
        let url = try #require(Bundle.module.url(
            forResource: "embeddinggemma2-reference", withExtension: "json", subdirectory: "Fixtures"
        ))
        return try JSONDecoder().decode(Reference.self, from: Data(contentsOf: url))
    }

    private func norm(_ v: [Double]) -> Double {
        v.reduce(0) { $0 + $1 * $1 }.squareRoot()
    }

    @Test("the fixture names the exact 8-bit revision and the model card's prompts")
    func provenance() throws {
        let ref = try load()
        #expect(ref.model == "mlx-community/embeddinggemma-2-8bit")
        #expect(ref.modelRevision == "7505ef2f8ddef45efef6d060865f27989b3c9cec")
        #expect(ref.prompts["query"] == "task: search result | query: ")
        #expect(ref.prompts["document"] == "title: none | text: ")
        for item in ref.cases {
            let prefix = try #require(ref.prompts[item.role])
            #expect(item.prompted.hasPrefix(prefix), "\(item.id)")
        }
    }

    @Test("every vector is unit length; the 512 is the re-normalised head of the 768")
    func vectors() throws {
        for item in try load().cases {
            #expect(item.embedding768.count == 768)
            #expect(item.embedding512.count == 512)
            #expect(abs(norm(item.embedding768) - 1) < 1e-3, "\(item.id)")
            #expect(abs(norm(item.embedding512) - 1) < 1e-3, "\(item.id)")
            let head = Array(item.embedding768.prefix(512))
            let headNorm = norm(head)
            let drift = zip(head, item.embedding512).map { abs($0 / headNorm - $1) }.max() ?? 1
            #expect(drift < 1e-4, "\(item.id) MRL truncation drift \(drift)")
        }
    }

    @Test("the tokenizer wraps every input in <bos>=2 … <eos>=1 — the port must too")
    func specialTokens() throws {
        for item in try load().cases {
            #expect(item.inputIDs.first == 2, "\(item.id)")
            #expect(item.inputIDs.last == 1, "\(item.id)")
        }
    }

    @Test("one document is longer than the 512-token sliding window, so the port's local mask is exercised")
    func longCasePresent() throws {
        let long = try #require(load().cases.first { $0.id == "d-long" })
        #expect(long.inputIDs.count > 512 * 2, "two full windows")
    }

    @Test("relevance order holds: each query is nearer its document than the off-topic one")
    func ranking() throws {
        let checks = try load().rankingChecks
        #expect(checks.count >= 4)
        let allRanked = checks.allSatisfy { $0.ok }
        #expect(allRanked)
    }
}
